[project]
name = "flet-instalador"
version = "0.1.0"
description = "FletInstalador control for Flet"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "Flet contributors", email = "you@example.com" }
]
dependencies = [
    "flet>=0.85.3",
]

[dependency-groups]
dev = [
    "mkdocs",
    "mkdocs-material",
    "mkdocstrings[python]"
]

[project.urls]
Homepage = "https://mydomain.dev"
Documentation = "https://github.com/MyGithubAccount/flet-instalador"
Repository = "https://github.com/MyGithubAccount/flet-instalador"
Issues = "https://github.com/MyGithubAccount/flet-instalador/issues"

[tool.setuptools.package-data]
"flutter.flet_instalador" = ["**/*"]

[tool.setuptools]
license-files = []

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
